title: 情報処理学会 数理モデル化と問題解決(MPS)研究会
short_title: MPS研究会
description: "IPSJ SIG-MPS: Mathematical Modeling and Problem Solving"
show_downloads: true
google_analytics: G-0HFQYJNEQ9
theme: jekyll-theme-cayman
collections:
  mps_docs:
    output: true
  mps_docs_old:
    output: true
  news:
    output: true
  tom_docs:
    output: true
timezone: Asia/Tokyo
# X のアカウント取得したので
x.username: MPS_IPSJ_PR

plugins:
  - jekyll-last-modified-at

# Option for last modified
last-modified-at:
  date-format: "%d-%b-%Y"

#
header_page_refs: ["mps_schedule", "tom", "contact"]
